on: [push, pull_request]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: buster
    name: Build on buster aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: buster

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt-get install build-essential qt5-qmake qtdeclarative5-dev qt5-default qttools5-dev-tools jackd2 libjack-jackd2-dev  qjackctl libqt5websockets5-dev
